std::string JSON_ITEMSMAG = "[\n"
                         "  {\n"
                         "    \"Category\": \"Mag\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 204004,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended SMG\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204005,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"Quickdraw SMG\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204006,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"Ex Quickdraw SMG\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204007,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Snipers\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204008,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"Quickdraw Snipers\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204009,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"Ex Quickdraw Snipers\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204011,\n"
                         "        \"itemClass\": \"BP_DJ_Large_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended AR\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204012,\n"
                         "        \"itemClass\": \"BP_DJ_Large_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"Quickdraw AR\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204013,\n"
                         "        \"itemClass\": \"BP_DJ_Large_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"Ex Quickdraw AR\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";

