std::string JSON_ITEMSNI = "[\n"
                         "  {\n"
                         "    \"Category\": \"Sniper\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 103001,\n"
                         "        \"itemClass\": \"BP_Sniper_Kar98k_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Kar98K\",\n"
                         "        \"itemTextColor\": \"0xFE00FFEF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103002,\n"
                         "        \"itemClass\": \"BP_Sniper_M24_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M24\",\n"
                         "        \"itemTextColor\": \"0xFE00FFEF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103003,\n"
                         "        \"itemClass\": \"BP_Sniper_AWM_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AWM\",\n"
                         "        \"itemTextColor\": \"0xFFFFFC00\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103004,\n"
                         "        \"itemClass\": \"BP_Sniper_SKS_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SKS\",\n"
                         "        \"itemTextColor\": \"0xFE00FFEF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103006,\n"
                         "        \"itemClass\": \"BP_Sniper_Mini14_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mini14\",\n"
                         "        \"itemTextColor\": \"0xFF11FF00\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103007,\n"
                         "        \"itemClass\": \"BP_WEP_Mk14_Pickup_C_1\",\n"
                         "        \"itemName\": \"Mk14\",\n"
                         "        \"itemTextColor\": \"0xFE00FFEF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103011,\n"
                         "        \"itemClass\": \"BP_Sniper_Mosin_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mosin Sniper\",\n"
                         "        \"itemTextColor\": \"0xFE00FFEF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";

