std::string JSON_ITEMSAMMO = "[\n"
                         "  {\n"
                         "    \"Category\": \"Ammo\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 301001,\n"
                         "        \"itemClass\": \"BP_Ammo_9mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"9mm\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 302001,\n"
                         "        \"itemClass\": \"BP_Ammo_762mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"7.62mm\",\n"
                         "        \"itemTextColor\": \"0xFE00FFEF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 303001,\n"
                         "        \"itemClass\": \"BP_Ammo_556mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"5.56mm\",\n"
                         "        \"itemTextColor\": \"0xFF11FF00\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 305001,\n"
                         "        \"itemClass\": \"BP_Ammo_45ACP_Pickup_C_1\",\n"
                         "        \"itemName\": \".45 ACP\",\n"
                         "        \"itemTextColor\": \"0xFFFFFFFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";

